--REGISTRO DE INSERT (DATOS)

SELECT * FROM APP  --> COMPLETO
SELECT * FROM CAPACITACION  --> COMPLETO
SELECT * FROM CATEGORIA_NEGOCIO --> COMPLETO
SELECT * FROM CONCURSO  --> COMPLETO
SELECT * FROM CURSO  --> COMPLETO
SELECT * FROM DIRECCION  --> COMPLETO
SELECT * FROM DISTRITO --> COMPLETO
SELECT * FROM EMPRENDEDOR  --> COMPLETO
SELECT * FROM ESTADO_CUENTA  --> COMPLETO
SELECT * FROM EVENTOS  --> COMPLETO
SELECT * FROM FACTURACION  --> COMPLETO
SELECT * FROM FEEDBACK  --> COMPLETO
SELECT * FROM HISTORICO_EMPRENDIMIENTO --> COMPLETO
SELECT * FROM MENTOR --> COMPLETO
SELECT * FROM NEGOCIO  --> COMPLETO
SELECT * FROM ORGANIZACION_PATROCINADORA  --> COMPLETO
SELECT * FROM PREMIOS_CONCURSO --> COMPLETO
SELECT * FROM RECURSOS --> COMPLETO
SELECT * FROM REDES_SOCIALES --> COMPLETO
SELECT * FROM SESION_MENTORIA --> COMPLETO
SELECT * FROM TIPO_CONCURSO --> COMPLETO
SELECT * FROM TIPO_USUARIO --> COMPLETO
SELECT * FROM USUARIO --> COMPLETO

DELETE FROM eventos;
